Repository operate-first/hitchhikers-guide, pull requests merged in 2021-09, with the labels that each got.

#15 feat: create tutorial for onboarding to cluster
  _toc.yml
  pages/onboarding_new_cluster.ipynb
Labels: size/XL, lgtm, approved

#102 fix: rename files to be more descriptive and fix headers
  _toc.yml
  pages/getting_started.ipynb
  pages/onboarding_project.ipynb
Labels: size/XS, lgtm, approved

#103 feat: Update cluster onboarding guide to support monitoring and better logical flow
  pages/onboarding_new_cluster.ipynb
Labels: size/XL, lgtm

#104 fix: KeycloakClient on the cluster onboarding
  pages/onboarding_new_cluster.ipynb
Labels: lgtm, size/L, approved
